# Generated by Django 3.2.13 on 2022-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Shelfish', 'Shelfish'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Wheat', 'Wheat'), ('Soy', 'Soy')], max_length=20, unique=True, verbose_name='Allergen name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('allergens', models.ManyToManyField(blank=True, to='restaurant.Allergen')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
