# Generated by Django 3.2.13 on 2022-05-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='Course',
        ),
    ]
