# Generated by Django 3.2.13 on 2022-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Starter', 'Starter'), ('Soup', 'Soup'), ('Salads', 'Salads'), ('Fish', 'Fish'), ('Main', 'Main'), ('Dessert', 'Dessert')], max_length=50, unique=True, verbose_name='Course type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Shelfish', 'Shelfish'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Wheat', 'Wheat'), ('Soy', 'Soy')], max_length=50, unique=True, verbose_name='Allergen name'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ManyToManyField(to='restaurant.Course_Type'),
        ),
    ]
