# Generated by Django 3.2.13 on 2022-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220521_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allergens',
        ),
        migrations.AddField(
            model_name='course',
            name='allergen_name',
            field=models.CharField(choices=[('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Shelfish', 'Shelfish'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Wheat', 'Wheat'), ('Soy', 'Soy')], default='None', max_length=50, unique=True, verbose_name='Allergen name'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Soup', 'Soup'), ('Salads', 'Salads'), ('Fish', 'Fish'), ('Main', 'Main'), ('Dessert', 'Dessert')], default='Starter', max_length=50, unique=True, verbose_name='Course type'),
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
        migrations.DeleteModel(
            name='Course_Type',
        ),
    ]
