# Generated by Django 3.2.13 on 2022-05-21 11:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20220521_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allergen_name',
        ),
        migrations.AddField(
            model_name='course',
            name='allergens',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'None'), (2, 'Dairy'), (3, 'Eggs'), (4, 'Fish'), (5, 'Shelfish'), (6, 'Nuts'), (7, 'Peanuts'), (8, 'Wheat'), (9, 'Soy')], default='None', max_length=17),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
