# Generated by Django 3.2.13 on 2022-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20220521_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Soup', 'Soup'), ('Salads', 'Salads'), ('Fish', 'Fish'), ('Main', 'Main'), ('Dessert', 'Dessert')], default='Starter', max_length=25, unique=True, verbose_name='Course type'),
        ),
    ]
