# Generated by Django 3.2.13 on 2022-06-06 17:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_eventform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
    ]
