# Generated by Django 3.2.13 on 2022-06-13 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0010_alter_eventform_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField(choices=[(datetime.time(17, 0), '17:00'), (datetime.time(17, 3), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 3), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 3), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 3), '20:30'), (datetime.time(21, 0), '21:00')], default=datetime.time(17, 0))),
                ('allergies', models.CharField(choices=[('No Allergies', 'No Allergies'), ('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Shelfish', 'Shellfish'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Gluten', 'Gluten'), ('Soy', 'Soy')], default='No Allergies', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'arrival_time'],
            },
        ),
    ]
