# Generated by Django 3.2.13 on 2022-06-15 18:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_booking_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('No Allergies', 'No Allergies'), ('Dairy', 'Dairy'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Shelfish', 'Shellfish'), ('Nuts', 'Nuts'), ('Peanuts', 'Peanuts'), ('Gluten', 'Gluten'), ('Soy', 'Soy')], default='No Allergies', max_length=61),
        ),
    ]
